### ISSUE TITLE
Please regenerate plugin from plugin template to clean up contributer list

### ISSUE THREAD

**Issue by CuteWaterBeary** [pteridin/obsidian_symlink_plugin#1]
Currently it shows up as 24 contributors when there's just one

**Comment by pteridin** [comment]
History is rewritten to only contain commits by myself. This should fix this issue afaik, but may take some time for github caching to update. I will wait 24 - 48 h and come back to this issue, unless you know that this will not yield the desired result.

**Comment by CuteWaterBeary** [comment]
It didnt seem to work... and I dont really know how to do it

**Comment by pteridin** [comment]
Apparently. And me neither. :) 

Let's wait for someone with more knowledge stumble upon this issue.

**Comment by pteridin** [comment]
Fixed. After cleaning the repository history a renaming of the branch updates the contributor list.
