### ISSUE TITLE
How can I create symlinks for files?

### ISSUE THREAD

**Issue by CuteWaterBeary** [pteridin/obsidian_symlink_plugin#2]
The manifest for this says "description": "Create symlinks to files and folders inside and outside of your vault.". 

How can I create symlinks for files? I dont really have a use for the folder symlinks. 

My use case for the file symlinks would be to be able to find the same file in different hierarchies through the tree view.

Theres a bunch of plugins that try to solve this using tags (breadcrumbs) and more complex ways (bearings) but I think the best and simplest way would be to just use symlinks so a file can appear in two folders when it fits in those 2 categories.

**Comment by pteridin** [comment]
Yes, I may have missed the "files" functionality. As of right now it can create symlinks to folders. 

On Linux/OS X it should be pretty straight forward to create symlinks to files as well. On Windows however `mklink` will require "Developer Mode" enabled or admin rights. 

Is that something that could work for you and is there some urgency for this functionality?

**Comment by CuteWaterBeary** [comment]
I would love it if I could create the symlinks to files so if you get to implementing this, I would use it right away.
